FROM redis:alpine

COPY ./infrastructure/configuration/redis/redis-production.conf /usr/local/etc/redis/redis-production.conf

EXPOSE 6379

CMD ["redis-server", "/usr/local/etc/redis/redis-production.conf"]
