services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: php artisan octane:frankenphp
        ports:
            - "80:8000"
        volumes:
            - .:/app
