FROM nginx:latest

USER root

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

CMD ["nginx", "-g", "daemon off;"]
