<div>
    <label>
        <input
            type="search"
            placeholder="Search"
            wire:model="searchTerm"
            wire:keydown.enter="search"
            class="search-field"
        >
    </label>
</div>
