<?php

namespace App\Filament\Pages;

use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use Filament\Pages\Page;
use ShuvroRoy\FilamentSpatieLaravelHealth\Pages\HealthCheckResults;

class ApplicationHealth extends HealthCheckResults
{
    use HasPageShield;
    public static function getNavigationGroup(): ?string
    {
        return "System"; // TODO: Change the autogenerated stub
    }

}
