<?php

namespace App\Filament\Pages;

use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use Filament\Pages\Page;

class Logs extends \FilipFonal\FilamentLogManager\Pages\Logs
{
    use HasPageShield;
    public static function getNavigationGroup(): ?string
    {
        return "System"; // TODO: Change the autogenerated stub
    }

}
