name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host Key to Known Hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -t rsa 65.109.56.190 >> $HOME/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh root@65.109.56.190 'bash -s < ~/deploy.sh'
